# docker-compose.yml example for https://github.com/ServerContainers/samba

services:
  samba:
    build: .
    image: ghcr.io/servercontainers/samba
    restart: always
    # note that this network_mode makes it super easy (especially for zeroconf) but is not as safe as exposing ports directly
    # more about that here: https://book.hacktricks.wiki/en/linux-hardening/privilege-escalation/docker-security/docker-breakout-privilege-escalation/index.html#hostnetwork
    # network_mode: host
    # uncomment to solve bug: https://github.com/ServerContainers/samba/issues/50 - wsdd2 only - not needed for samba
    # cap_add:
    #  - CAP_NET_ADMIN
    ports:
      - 445:445
      - 139:139
      - 3702:3702
      - 5353:5353
      - 5355:5355
    environment:
      # uncomment to enable fail fast (currently only fails fast if there are conflicts/errors during user/group creation)
      #FAIL_FAST: 1
      MODEL: 'TimeCapsule'
      AVAHI_NAME: StorageServer
      SAMBA_CONF_LOG_LEVEL: 3
      # uncomment to disable optional services
      #WSDD2_DISABLE: 1
      #AVAHI_DISABLE: 1
      #NETBIOS_DISABLE: 1

    volumes:
      # This assumes you're running avahi externally
      # - /etc/avahi/services/:/external/avahi
      
      # avoid loops when mounting folders to /shares (I'd recommend explicit mapping for each share)
      - /Volumes/LocalMedia/testshare/:/shares/testshare
      - ./conf/smb.conf:/etc/samba/smb.conf
      
